on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: wr-porini/private-repo-test
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
